<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ButtonUpload</name>
   <tag></tag>
   <elementGuidId>31beacff-f6a9-4e51-9fdf-40aaa5256986</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;form-mcu-registrasi-perusahaan&quot;]/div[1]/div[2]/div/div/div/div/div[1]/div/div[2]/div/div[2]/div[2]/div/div[1]/div/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
