<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kata Sandi_kata-sandi</name>
   <tag></tag>
   <elementGuidId>806b5839-8c17-4c04-ac4b-b112a1dc1259</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kata-sandi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kata-sandi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07a973bc-b302-4b6f-8279-a25109b9459a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>fd3b9509-cdda-4ac8-9d4e-715e99a6754a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-2 py-1 outline-1 outline-[#0A8FDC] font-medium py-[0.5rem] text-sm outline-0 border-none</value>
      <webElementGuid>a9387d2f-9f40-4004-b37d-fe8ab5b7dfa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kata-sandi</value>
      <webElementGuid>535c8d2c-54cf-4cf2-aa95-2cf93bf0242e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>********</value>
      <webElementGuid>b57374ee-1151-4186-ba47-a5945b48fb70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kata-sandi&quot;)</value>
      <webElementGuid>de974c84-f1b9-40a4-866e-5eedcf06ff27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kata-sandi']</value>
      <webElementGuid>32ba7bb4-1fb7-4e3e-a808-fc76d16a0655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/form/div/div[2]/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>a191294a-89f7-4223-a3cc-3cb8c4528e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>49d0f9fa-dda0-45e1-bb74-83349da898e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'kata-sandi' and @placeholder = '********']</value>
      <webElementGuid>92e6d61b-225e-4e77-8aeb-e2fac67c681d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
