<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kata Sandi_kata-sandi</name>
   <tag></tag>
   <elementGuidId>ebe7dc4a-72f4-4a5a-b47a-853b015a812e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kata-sandi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kata-sandi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;********&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a62948d9-050d-4c00-8d64-fc81935d04cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>efe6e0d7-6435-4213-bcac-52f171f7b3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-2 py-1 outline-1 outline-[#0A8FDC] font-medium py-[0.5rem] text-sm outline-0 border-none</value>
      <webElementGuid>029aec48-8e42-46aa-a2fe-f7866426f0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kata-sandi</value>
      <webElementGuid>8970259e-c3d3-4f48-a904-81ad53d587f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>********</value>
      <webElementGuid>026f9cc7-7ded-4ccf-9711-20fa8bb9821e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kata-sandi&quot;)</value>
      <webElementGuid>c424bb68-711b-4c48-9491-ccf0b8500684</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kata-sandi']</value>
      <webElementGuid>a90ae457-76c8-4c64-94f8-21a0688909b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/form/div/div[2]/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>6eee0a12-6a41-420f-9299-c305b9195bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>444616c9-592c-42e2-88e2-0085dab63aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'kata-sandi' and @placeholder = '********']</value>
      <webElementGuid>289d8f40-ae59-44be-a7bb-a8621225dde2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
