<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NIK_nik</name>
   <tag></tag>
   <elementGuidId>0473ebb5-238a-466a-9e79-d5f9d5754f07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nik</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nik']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukan NIK (Nomor Induk Kepagawaian)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9a01f1e-62f0-40dc-a5e0-a3ebaaa62adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef528917-2cbc-4fc3-9d96-c900b5b23eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-2 py-1 outline-1 outline-[#0A8FDC] font-medium py-[0.5rem] text-sm outline-0 border-none</value>
      <webElementGuid>6d9b72ed-f582-4d07-b8f2-501bcac10ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nik</value>
      <webElementGuid>0563de7b-4d9a-4d9e-978d-921e9d965282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan NIK (Nomor Induk Kepagawaian)</value>
      <webElementGuid>189f7a9c-db33-4602-9c1e-147de2290a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nik&quot;)</value>
      <webElementGuid>4f573c64-6532-4d8f-bb37-e956e228d711</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nik']</value>
      <webElementGuid>e1199742-4830-4816-829b-7d321a4d21cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/form/div/div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>0de73bb6-5750-4974-8448-39fa0702a348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>69e48ee1-a000-4c10-9a98-e3f2838ca585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nik' and @placeholder = 'Masukan NIK (Nomor Induk Kepagawaian)']</value>
      <webElementGuid>2fe2497c-9034-4bfc-8968-017ee5ab887e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
