<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Superadmin</name>
   <tag></tag>
   <elementGuidId>17b095ef-43cb-4c1e-a8bb-a685dea27b26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SUPER']/div/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.font-semibold.capitalize</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Superadmin&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>fec81e9d-dcee-400b-88a8-3f9ebcffdd36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-semibold capitalize</value>
      <webElementGuid>2a370411-90da-4bd0-8bbc-adfa4ca24aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Superadmin</value>
      <webElementGuid>0bf3c4ec-9028-425a-9046-4e6257235f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SUPER&quot;)/div[@class=&quot;py-3 gap-x-4 items-center&quot;]/div[2]/p[@class=&quot;font-semibold capitalize&quot;]</value>
      <webElementGuid>e8969fec-4588-4f41-aad9-ddf7d2e73e0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SUPER']/div/div[2]/p</value>
      <webElementGuid>9a937d53-1e84-403b-8cce-a1e638e68e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata Sandi'])[1]/following::p[4]</value>
      <webElementGuid>9fc74ada-3b25-4d2b-8027-61f25df7cc78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kebijakan aplikasi'])[1]/preceding::p[2]</value>
      <webElementGuid>8b70f1f5-3c58-44ac-abc7-c0bbd2b4fa6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='persyaratan'])[1]/preceding::p[2]</value>
      <webElementGuid>1bdad362-7ca7-408b-8b6e-798634cd21a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Superadmin']/parent::*</value>
      <webElementGuid>e9acb4f9-f713-428f-a1fe-3ded2c98a14a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/p</value>
      <webElementGuid>b869ddfc-65ea-4bb6-9ae7-76285f3ea734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Superadmin' or . = 'Superadmin')]</value>
      <webElementGuid>ad9685d8-f75a-44d1-8be1-27227bb0c02f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
