<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah</name>
   <tag></tag>
   <elementGuidId>1640f348-974c-4be8-8427-0901a087a075</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Tambah&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b5bf4eb0-0f5a-4afd-afbd-e1a7bdb0387a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center gap-x-2 text-white  py-[4px] px-[8px] text-xxs rounded-[3px] font-medium css-o55cv1</value>
      <webElementGuid>bfad5997-62e2-46ae-a3a9-cd826cbcb0c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>97efe45a-1bff-4234-9539-d318f39ccc11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tambah</value>
      <webElementGuid>7334e6cd-b4d7-4645-9120-3aa3994af67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-wrapper&quot;)/div[@class=&quot;MuiBox-root css-k008qs&quot;]/main[@class=&quot;MuiBox-root css-guogeh&quot;]/div[@class=&quot;mt-8 wrapper&quot;]/main[1]/div[1]/div[@class=&quot;grid grid-flow-col auto-cols-max gap-x-2&quot;]/div[2]/div[@class=&quot;h-full w-full rounded-t-lg&quot;]/div[2]/div[@class=&quot;p-4&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-2 css-isbt42&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-md-12 css-we0np1&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-2 css-isbt42&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-md-6 css-8pdr4s&quot;]/form[1]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-1 css-tuxzvu&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-md-12 css-we0np1&quot;]/div[@class=&quot;-mt-1&quot;]/div[@class=&quot;flex justify-end mt-3 gap-x-2&quot;]/button[@class=&quot;flex items-center gap-x-2 text-white  py-[4px] px-[8px] text-xxs rounded-[3px] font-medium css-o55cv1&quot;]</value>
      <webElementGuid>5c140bce-415b-4248-8195-cc1af364ebaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>db27b727-f9a3-4f69-95b9-e75c9caddc19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app-wrapper']/div/main/div/main/div/div/div[2]/div/div[2]/div/div/div[4]/div/div/form/div/div[4]/div/div/button[2]</value>
      <webElementGuid>a4450f77-51ee-4fe2-8e6d-e050e940924f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[3]/following::button[2]</value>
      <webElementGuid>8369612e-9e9a-4a76-9bbc-4efb998a7ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAFTAR TEST'])[1]/preceding::button[1]</value>
      <webElementGuid>c1c21a3c-061a-46ef-859c-1f8379963541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/button[2]</value>
      <webElementGuid>c5a9c7f3-1657-489c-9ef5-0132ec6f0fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = ' Tambah' or . = ' Tambah')]</value>
      <webElementGuid>5ff2c9a9-b8e6-44f5-b2ee-7ea4b017f554</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
