<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Awal_tanggal_awal</name>
   <tag></tag>
   <elementGuidId>da528a60-94bb-40f3-a004-c5636e137790</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tanggal_awal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tanggal_awal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46793351-f6e9-452d-b22a-d376e1fa51d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7b8690d9-0722-4402-ac9d-c13e4fef8adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-2 py-1 outline-1 outline-[#0A8FDC] font-medium react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>6d5fb0a8-d78f-4bc9-ad2e-c36f1b2f7e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tanggal Awal</value>
      <webElementGuid>90bbde38-b5c9-4fa2-bd12-54f552e3077a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tanggal_awal</value>
      <webElementGuid>5863aa8a-644c-47c0-9339-5aac2ecfc7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>58737ee0-25e1-4282-b37c-5d6ae6e42baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tanggal_awal&quot;)</value>
      <webElementGuid>7ce7674f-dcee-4785-ba3e-1aea7a8276a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tanggal_awal']</value>
      <webElementGuid>7afbd3e0-aeb6-4e38-98ba-bd62fb940b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='7433d201-a710-4b00-8b15-f1a3529ba401']/div[3]/div/div/form/div/div[4]/div/div/div/div/div/input</value>
      <webElementGuid>287068e1-7fa5-4ae5-b57b-aa05052abf11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/form/div/div[4]/div/div/div/div/div/input</value>
      <webElementGuid>a9f1e2f9-9ef6-4938-9c0c-82b380b6c4ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Tanggal Awal' and @id = 'tanggal_awal']</value>
      <webElementGuid>3417adb5-6ce3-4fb1-96a7-67e666fa9f4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
