<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Pasien  No. RM_search_key</name>
   <tag></tag>
   <elementGuidId>d5eb0bd5-a9cb-4450-946d-bb3ff3c9711d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='search_key'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4b60ba6-8292-429b-8c48-3b71c616f070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2efbbb3a-0485-4b90-a879-c198096d30c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-2 py-1 outline-1 outline-[#0A8FDC] font-medium</value>
      <webElementGuid>508aaba3-70df-4135-bc00-78030d6aef79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_key</value>
      <webElementGuid>3c0fd682-652e-42e2-ad80-d9480ba46246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Pasien / No. RM</value>
      <webElementGuid>5ca06a52-f7f6-4950-a9ca-9ce728891a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_key</value>
      <webElementGuid>076e295c-ebbd-43e0-a645-dcda92653cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7433d201-a710-4b00-8b15-f1a3529ba401&quot;)/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper css-ekeie0&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation24 MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthLg MuiDialog-paperFullWidth css-1nhstuc&quot;]/div[@class=&quot;MuiDialogContent-root css-1ty026z&quot;]/form[1]/div[@class=&quot;grid grid-cols-3 gap-x-1 gap-y-2 my-2&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full grid grid-cols-12 rounded-sm bg-white items-center text-[0.7rem] border&quot;]/div[@class=&quot;col-span-12&quot;]/input[@id=&quot;search_key&quot;]</value>
      <webElementGuid>6e47e081-7cec-4be0-8d39-28d476a24382</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='search_key'])[2]</value>
      <webElementGuid>ef38a515-9737-4716-97ce-91e215e7a9db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='7433d201-a710-4b00-8b15-f1a3529ba401']/div[3]/div/div/form/div/div/div/div/div/input</value>
      <webElementGuid>275089c4-6be7-4f2b-a190-e77aa16d3c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/input</value>
      <webElementGuid>e84ddeaa-10cc-4f38-b98f-1cbfd2b94c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'search_key' and @placeholder = 'Nama Pasien / No. RM' and @name = 'search_key']</value>
      <webElementGuid>c68088f6-0b2d-4829-955a-30e0dd44f961</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
