<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Akhir_tanggal_akhir</name>
   <tag></tag>
   <elementGuidId>9d320e1e-c7f3-417e-942d-0030f04b801d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tanggal_akhir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tanggal_akhir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81ae7928-bb23-4510-a124-4114f5c2e8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f4699f1e-8a22-42c6-8674-63e5b5c8c45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-2 py-1 outline-1 outline-[#0A8FDC] font-medium react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>8bcedcb8-bfc7-4ec4-b6e7-335e5869bc29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tanggal Akhir</value>
      <webElementGuid>505a9ad6-3394-4652-b5d7-2dd9ec872c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tanggal_akhir</value>
      <webElementGuid>4679e7e6-9d66-46b4-90cb-be6b672c33f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>decc6db9-7079-4870-a0f8-59bf516acefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tanggal_akhir&quot;)</value>
      <webElementGuid>7d366a95-d33f-4d1f-b7ad-c2f38e2a7560</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tanggal_akhir']</value>
      <webElementGuid>b8fd5326-eec9-41d4-a19f-28c43109ff26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='7433d201-a710-4b00-8b15-f1a3529ba401']/div[3]/div/div/form/div/div[5]/div/div/div/div/div/input</value>
      <webElementGuid>3c820551-033d-4a2a-9c47-fa31535590fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/form/div/div[5]/div/div/div/div/div/input</value>
      <webElementGuid>78920c04-17cb-4482-92ba-0270608d4e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Tanggal Akhir' and @id = 'tanggal_akhir']</value>
      <webElementGuid>a2e1ec5f-868e-43be-8fa4-a2a6801abdc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
