<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>1479cf53-d104-4bb6-987f-7755b1575090</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>c687103a-11c0-4a92-b3c2-c8e08dc59237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>98f3810e-5081-4451-8d28-673220c243bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M20.71 7.04c.39-.39.39-1.04 0-1.41l-2.34-2.34c-.37-.39-1.02-.39-1.41 0l-1.84 1.83l3.75 3.75M3 17.25V21h3.75L17.81 9.93l-3.75-3.75z</value>
      <webElementGuid>6aec92b6-1e42-4496-88fa-5c0760bf9939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-mcu-registrasi-perusahaan&quot;)/div[@class=&quot;simplebar-wrapper&quot;]/div[@class=&quot;simplebar-mask&quot;]/div[@class=&quot;simplebar-offset&quot;]/div[@class=&quot;simplebar-content-wrapper&quot;]/div[@class=&quot;simplebar-content&quot;]/div[@class=&quot;space-y-3&quot;]/div[@class=&quot;bg-white pb-3 pt-1 px-3 shadow-sm rounded-md&quot;]/div[@class=&quot;simplebar-scrollable-x simplebar-scrollable-y&quot;]/div[@class=&quot;simplebar-wrapper&quot;]/div[@class=&quot;simplebar-mask&quot;]/div[@class=&quot;simplebar-offset&quot;]/div[@class=&quot;simplebar-content-wrapper&quot;]/div[@class=&quot;simplebar-content&quot;]/table[@class=&quot;w-full relative asha-datatable table-fixed&quot;]/tbody[1]/tr[@class=&quot;border-gray-400 hover:bg-blue-50 py-1 odd:bg-white even:bg-slate-50&quot;]/td[@class=&quot;border border-gray-200 text-xs py-1 px-2 font-medium text-black text-center align-top&quot;]/div[@class=&quot;flex flex-row justify-center items-center gap-1&quot;]/button[@class=&quot;rounded flex items-center justify-center py-1 px-1 w-5 relative  h-5 w-5&quot;]/svg[@class=&quot;iconify iconify--mdi&quot;]/path[1]</value>
      <webElementGuid>102911e2-74a2-4f25-823c-36f77dc4e4f0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
