<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VerifyLabelTabel</name>
   <tag></tag>
   <elementGuidId>1f0c69ba-1432-4009-9141-6ee052481121</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;daftar-paket&quot;]/div[2]/div[1]/div[2]/div/div[1]/div[2]/div/div/div/div/div/div[2]/div[2]/div/div[1]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
