<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IconEditForm</name>
   <tag></tag>
   <elementGuidId>ea7c8da7-a1c1-4657-b3df-588b9c58bc3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app-wrapper&quot;]/div/main/div/main/div/div/div/div[1]/div[3]/div/div[1]/div[2]/div/div/div/div/div[2]/div/div/div[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
