<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>create</description>
   <name>InputNamaFormCreate</name>
   <tag></tag>
   <elementGuidId>1058da69-8133-4baa-9f95-91aba371a38b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;nama_form_mcu&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
