<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>create</description>
   <name>InputKeteranganFormCreate</name>
   <tag></tag>
   <elementGuidId>c3a83567-894d-46bc-a887-d8ca78c4d6b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div[3]/div/div/form/div[1]/div[3]/div/div[2]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
